### ISSUE TITLE
API serves files without extension

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/CHoice#25]
Currently, the API serves PDF exams at endpoints like `/api/v1/document/exam/9`. Some browsers (e.g. Firefox Developer Edition) do not append an extension to the filename, so you end up with a file called `9` instead of `9.pdf`.

It would be even better to change the name of the downloaded file to `[filename].pdf` instead of `[id](.pdf)`.

**Comment by jgadelange** [comment]
I think it would be better to set the `content-disposistion` header with a filename

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
