### ISSUE TITLE
Fix not being able to add new exams

### ISSUE THREAD

**Issue by ricardovogel** [WISVCH/CHoice#53]
The TU Delft API is deprecated and should be decoupled from this project.

**Comment by ricardovogel** [comment]
HootHub doesn't have rights to this repo, so I can't assign it the HootHub label or add it to the HootHub project.

**Comment by Zedfrigg** [comment]
There was no TU Delft API integration preventing exams from being added. The problem is caused by an unknown bug in production, which as of yet I've not been able to reproduce.
